name: Tests
on:
  push:
env:
  PYTHONPATH: src
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run Unit Tests
      run: python -m unittest tests.unit_test
  DB-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run DB Tests
      run: python -m unittest tests.db_test